import Content from "./components/Content";
function ResearchPage(){
    return(
        <div className="w-full flex flex-col justify-center items-center py-14">
            <div className="w-4/5 justify-start items-start pb-14">
            <h1 className="font-roboto text-lg text-[#4e443c]">Research</h1>
            </div>
           <div className="w-4/5 grid grid-cols-2 gap-y-14 justify-center items-center lg:grid-cols-3">
                <Content bg="bg-[#dfd9d8]"
                beBorderFirst="before:border-t-transparent"
                beBorderSecound="before:border-r-transparent"
                beBorderThird="before:border-b-[#dfd9d8]"
                beBorderFour="before:border-l-transparent"
                afBorderFirst="after:border-t-[#dfd9d8]"
                afBorderSecound="after:border-r-transparent"
                afBorderThird="after:border-b-transparent"
                afBorderFour="after:border-l-transparent"
                borderX = "border-x-[#e5e7eb]"
                borderT = "border-t-[#e5e7eb]"
                borderB = "border-b-[#dfd9d8]"
                borderWX = "border-x-1"
                borderWT = "border-t-1"
                borderWB = "border-b-2"
                />
                <Content bg="bg-[#c8dbd0]"
                beBorderFirst="before:border-t-transparent"
                beBorderSecound="before:border-r-transparent"
                beBorderThird="before:border-b-[#c8dbd0]"
                beBorderFour="before:border-l-transparent"
                afBorderFirst="after:border-t-[#c8dbd0]"
                afBorderSecound="after:border-r-transparent"
                afBorderThird="after:border-b-transparent"
                afBorderFour="after:border-l-transparent"
                borderX = "border-x-[#e5e7eb]"
                borderT = "border-t-[#e5e7eb]"
                borderB = "border-b-[#c8dbd0]"
                borderWX = "border-x-1"
                borderWT = "border-t-1"
                borderWB = "border-b-2"
                />
                <Content bg="bg-[#eab1b8]"
                beBorderFirst="before:border-t-transparent"
                beBorderSecound="before:border-r-transparent"
                beBorderThird="before:border-b-[#eab1b8]"
                beBorderFour="before:border-l-transparent"
                afBorderFirst="after:border-t-[#eab1b8]"
                afBorderSecound="after:border-r-transparent"
                afBorderThird="after:border-b-transparent"
                afBorderFour="after:border-l-transparent"
                borderX = "border-x-[#e5e7eb]"
                borderT = "border-t-[#e5e7eb]"
                borderB = "border-b-[#eab1b8]"
                borderWX = "border-x-1"
                borderWT = "border-t-1"
                borderWB = "border-b-2"
                />
                <Content bg="bg-[#8bc3c4]"
                beBorderFirst="before:border-t-transparent"
                beBorderSecound="before:border-r-transparent"
                beBorderThird="before:border-b-[#8bc3c4]"
                beBorderFour="before:border-l-transparent"
                afBorderFirst="after:border-t-[#8bc3c4]"
                afBorderSecound="after:border-r-transparent"
                afBorderThird="after:border-b-transparent"
                afBorderFour="after:border-l-transparent"
                borderX = "border-x-[#e5e7eb]"
                borderT = "border-t-[#e5e7eb]"
                borderB = "border-b-[#8bc3c4]"
                borderWX = "border-x-1"
                borderWT = "border-t-1"
                borderWB = "border-b-2"
                />
                <Content bg="bg-[#eae098]"
                beBorderFirst="before:border-t-transparent"
                beBorderSecound="before:border-r-transparent"
                beBorderThird="before:border-b-[#eae098]"
                beBorderFour="before:border-l-transparent"
                afBorderFirst="after:border-t-[#eae098]"
                afBorderSecound="after:border-r-transparent"
                afBorderThird="after:border-b-transparent"
                afBorderFour="after:border-l-transparent"
                borderX = "border-x-[#e5e7eb]"
                borderT = "border-t-[#e5e7eb]"
                borderB = "border-b-[#eae098]"
                borderWX = "border-x-1"
                borderWT = "border-t-1"
                borderWB = "border-b-2"
                />
                <Content bg="bg-[#3088a7]"
                beBorderFirst="before:border-t-transparent"
                beBorderSecound="before:border-r-transparent"
                beBorderThird="before:border-b-[#3088a7]"
                beBorderFour="before:border-l-transparent"
                afBorderFirst="after:border-t-[#3088a7]"
                afBorderSecound="after:border-r-transparent"
                afBorderThird="after:border-b-transparent"
                afBorderFour="after:border-l-transparent"
                borderX = "border-x-[#e5e7eb]"
                borderT = "border-t-[#e5e7eb]"
                borderB = "border-b-[#3088a7]"
                borderWX = "border-x-1"
                borderWT = "border-t-1"
                borderWB = "border-b-2"
                />
            </div>
        </div>
    );
}

export default ResearchPage